# Generated by Django 3.2.8 on 2022-03-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlist_bids_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='starting_bid',
            field=models.IntegerField(),
        ),
    ]
