# Generated by Django 3.2.8 on 2022-03-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlist_starting_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlist',
            old_name='image',
            new_name='image_link',
        ),
    ]
